---
font: jetbrains mono
font_size: 10
font_icon: 
  - FontAwesome5FreeRegular
  - FontAwesome5FreeSolid
  - FontAwesome5Brands
gtk_theme: Adwaita-dark
icon_theme: Papirus-Dark
git_name: eoli3n
git_mail: jonathan.kirszling@runbox.com
caldav: https://dav.runbox.com/

# Black + DarkGrey
color0:  '#282a36'
color8:  '#686868'
# DarkRed + Red
color1:  '#ff5c57'
color9:  '#ff5c57'
# DarkGreen + Green
color2:  '#5af78e'
color10: '#5af78e'
# DarkYellow + Yellow
color3:  '#f3f99d'
color11: '#f3f99d'
# DarkBlue + Blue
color4:  '#57c7ff'
color12: '#57c7ff'
# DarkMagenta + Magenta
color5:  '#ff6ac1'
color13: '#ff6ac1'
# DarkCyan + Cyan
color6:  '#9aedfe'
color14: '#9aedfe'
# LightGrey + White
color7:  '#eff0eb'
color15: '#f1f1f0'
